version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_news
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5433"
    command: ["postgres", "-p", "5433"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_db_wrapper.sh:/docker-entrypoint-initdb.d/init_db_wrapper.sh

  news_collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_collector
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: ["python", "news_collector.py"]

volumes:
  postgres_data:
